const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = process.env.TESTPB_CDP ? await chromium.connectOverCDP(process.env.TESTPB_CDP) : await chromium.launch({ channel:'chrome', headless:true });
  const page = process.env.TESTPB_CDP ? browser.contexts()[0].pages()[0] : await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[]; page.on('pageerror',error=>errors.push(error.stack));
  const shot=async name=>{await page.waitForTimeout(100);await page.screenshot({path:`test-results/growth-${name}.png`});};
  const idle=()=>page.waitForFunction(()=>document.querySelector('#game')?.getAttribute('aria-busy')==='false'&&!document.querySelector('#game')?.classList.contains('dealing-hand'));
  const tile=(x,y)=>page.locator(`.tile[data-x="${x}"][data-y="${y}"]`);
  const select=async id=>{await idle();await page.locator(`#hand [data-card="${id}"]`).first().click();};
  const cycle=async()=>{await idle();await page.locator('[data-test-action="cycle"]').click();await idle();};
  const home=async()=>{await idle();await page.locator('#open-battle-help').click();await page.locator('#back-home').click();await page.locator('.screen-curtain').waitFor({state:'hidden'});};
  const start=async()=>{await page.locator('#open-dungeons').click();await page.locator('#start-game').click();await page.locator('.screen-curtain').waitFor({state:'hidden'});await idle();};
  try {
    await page.addInitScript(()=>{Math.random=()=>1/4294967296;});
    await page.goto('http://127.0.0.1:1420');
    await page.locator('#open-shop').click();await page.locator('.screen-curtain').waitFor({state:'hidden'});
    await shot('shop');
    assert.equal(await page.locator('.shop-card-choice').count(),5);
    await page.locator('.shop-card-choice[data-card="sidestep"]').click();
    assert.equal(await page.locator('#shop-engravings .shop-offer').count(),1);
    await page.getByRole('button',{name:/購買流轉/}).click();
    assert.equal(await page.locator('#shop-coins').textContent(),'1');
    await shot('shop-purchased');
    await page.locator('[data-shop-tab="gear"]').click();await shot('shop-gear');
    await page.locator('#shop-home').click();await start();await cycle();
    await page.locator('#open-deck').click();
    assert.equal(await page.locator('.deck-entry').count(),5);
    assert.match(await page.locator('.deck-entry[data-card="sidestep"]').textContent(),/流轉/);
    await shot('deck');
    await page.locator('[data-pile="discard"]').click();assert.equal(await page.locator('.deck-empty').count(),1);
    await page.locator('.deck-close').click();
    await select('repel');await tile(2,2).hover();
    assert.equal(await page.locator('#ghost').isHidden(),true);
    assert.equal(await page.locator('#push-ghost').isVisible(),true);
    assert.match(await page.locator('#push-ghost').evaluate(el=>el.style.top),/30%/);
    assert.equal(await page.locator('.target-health .forecast').count(),1);
    await shot('repel-preview');
    await tile(2,2).click();await idle();
    assert.match(await page.locator('[data-actor="0"]').evaluate(el=>el.style.top),/30%/);
    await cycle();await select('sidestep');await tile(1,1).hover();await shot('sidestep-preview');
    await tile(1,1).click();await idle();assert.equal(await page.locator('#hand .card').count(),5);
    assert.equal(await page.locator('#energy-count').getAttribute('data-value'),'5');
    await cycle();await select('sweep');await tile(2,1).hover();
    assert.equal(await page.locator('.area-target-mark').count(),1);assert.equal(await page.locator('.target-mark').count(),0);
    await shot('sweep-preview');
    await cycle();await select('sidestep');await tile(3,1).click();await idle();await select('thrust');await tile(3,2).hover();
    assert.equal(await page.locator('.block-preview').count(),1);
    assert.equal(await page.locator('.forecast-shield').count(),1);await shot('block-preview');
    await tile(3,2).click();await idle();
    await home();await page.locator('#open-characters').click();await page.locator('[data-character="rogue"]').click();await page.locator('#close-characters').click();
    await page.locator('#open-shop').click();await page.locator('.screen-curtain').waitFor({state:'hidden'});
    await page.locator('[data-shop-tab="cards"]').click();assert.equal(await page.locator('.shop-card-choice').count(),4);await shot('rogue-shop');
    await page.locator('#shop-home').click();await start();
    await page.locator('[data-test-action="elite"]').click();await idle();await home();
    await page.locator('#open-shop').click();await page.locator('.screen-curtain').waitFor({state:'hidden'});
    await page.locator('[data-shop-tab="gear"]').click();await page.getByRole('button',{name:/購買回刃扣/}).click();
    assert.equal(await page.locator('#shop-coins').textContent(),'5');
    await page.locator('#shop-home').click();await start();await cycle();
    await select('recall');await tile(0,1).hover();assert.equal(await page.locator('#ghost').isHidden(),true);
    assert.equal(await tile(2,2).evaluate(el=>el.classList.contains('legal')),false);await shot('recall-preview');
    await page.evaluate(()=>{window.overflowActivations=0;const node=document.querySelector('#overflow-feedback');window.overflowWatcher=new MutationObserver(changes=>{window.overflowActivations+=changes.filter(c=>c.attributeName==='hidden'&&!node.hidden).length;});window.overflowWatcher.observe(node,{attributes:true,attributeFilter:['hidden']});});
    await tile(0,1).click();await page.locator('#overflow-feedback').waitFor({state:'visible'});await shot('recall-overflow');await idle();
    assert.equal(await page.evaluate(()=>{window.overflowWatcher.disconnect();return window.overflowActivations;}),2);
    assert.equal(await page.locator('#hand .card').count(),5);assert.equal(await page.locator('.ground-knife[data-point="0,1"]').count(),0);
    assert.equal(await page.locator('#energy-count').getAttribute('data-value'),'6');
    await page.locator('#open-deck').click();await shot('rogue-deck');await page.locator('.deck-close').click();
    await cycle();await page.locator('[data-test-action="charge"]').click();await page.locator('#actions').click();
    await page.locator('#ultimate-reveal').waitFor({state:'visible'});await page.waitForTimeout(230);await shot('ultimate-reveal');
    await idle();await tile(2,2).hover();assert.equal(await page.locator('#ghost').isHidden(),true);await shot('ultimate-survivor');
    await tile(2,2).click();await idle();assert.equal(await page.locator('#hand .card').count(),5);
    assert.match(await page.locator('[data-actor="hero"]').evaluate(el=>el.style.top),/70%/);
    assert.deepEqual(errors,[]); console.log('Growth shop, both character cycles, forecasts, overflow, deck viewer: passed');
  } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exitCode=1;});
