const { chromium } = require('playwright');
const assert = require('node:assert/strict');

(async () => {
  const browser = process.env.TESTPB_CDP
    ? await chromium.connectOverCDP(process.env.TESTPB_CDP)
    : await chromium.launch({ channel: 'chrome', headless: true });
  const page = process.env.TESTPB_CDP
    ? browser.contexts()[0].pages()[0]
    : await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.stack));
  try {
    await page.addInitScript(() => { Math.random = () => 1 / 4294967296; });
    await page.goto('http://127.0.0.1:1420');
    await page.locator('#home-portrait').waitFor();
    assert.match(await page.locator('#home-portrait').getAttribute('src'), /qinghe/);
    await page.screenshot({ path: 'test-results/qinghe-home.png' });
    await page.locator('#open-characters').click();
    assert.equal(await page.locator('.character-choice').count(), 2);
    await page.waitForFunction(() => [...document.querySelectorAll('.character-choice img')].every(image => image.complete && image.naturalWidth > 0));
    await page.screenshot({ path: 'test-results/qinghe-character-picker.png' });
    await page.locator('[data-character="rogue"]').click();
    assert.match(await page.locator('#home-portrait').getAttribute('src'), /luxue/);
    await page.locator('[data-character="qinghe"]').click();
    assert.match(await page.locator('#home-portrait').getAttribute('src'), /qinghe/);
    await page.locator('#close-characters').click();
    await page.locator('#open-dungeons').click();
    await page.locator('#start-game').click();
    await page.locator('.screen-curtain').waitFor({ state: 'hidden' });
    await page.waitForFunction(() => [...document.images].filter(image => image.getAttribute('src')).every(image => image.complete && image.naturalWidth > 0));
    const openingHand = await page.locator('.card').evaluateAll(cards => cards.map(card => card.dataset.card));
    assert.equal(openingHand.length, 3);
    assert.ok(openingHand.every(id => ['advance', 'thrust', 'sweep'].includes(id)));
    assert.match(await page.locator('#actions').getAttribute('aria-label'), /破曉一槍/);
    await page.screenshot({ path: 'test-results/qinghe-opening.png' });
    await page.locator('[data-test-action="charge"]').click();
    await page.locator('#actions').click();
    await page.locator('#ultimate-reveal').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-card="dawnSpear"]').count(), 0);
    await page.waitForTimeout(280);
    await page.screenshot({ path: 'test-results/qinghe-ultimate-reveal.png' });
    await page.locator('#ultimate-reveal').waitFor({ state: 'hidden' });
    await page.locator('.ultimate-draw-card').waitFor({ state: 'visible' });
    await page.waitForTimeout(200);
    await page.screenshot({ path: 'test-results/qinghe-ultimate-draw.png' });
    await page.locator('.ultimate-draw-card').waitFor({ state: 'hidden' });
    await page.waitForFunction(() => document.getElementById('game')?.getAttribute('aria-busy') === 'false');
    assert.equal(await page.locator('[data-card="dawnSpear"]').count(), 1);
    await page.waitForFunction(() => [...document.images].filter(image => image.getAttribute('src')).every(image => image.complete && image.naturalWidth > 0));
    await page.locator('[data-card="dawnSpear"]').click();
    assert.equal(await page.locator('.tile.dawn-range').count(), 4);
    await page.locator('.tile[data-x="2"][data-y="3"]').hover();
    assert.equal(await page.locator('.tile.dawn-active').count(), 4);
    assert.equal(await page.locator('[data-actor="0"].victim-preview').count(), 1);
    await page.screenshot({ path: 'test-results/qinghe-dawn-preview.png' });
    await page.locator('.tile[data-x="2"][data-y="2"]').click();
    await page.waitForFunction(() => document.getElementById('game')?.getAttribute('aria-busy') === 'false');
    assert.match(await page.locator('#actions').getAttribute('aria-label'), /充能 0 \/ 4/);
    assert.equal(await page.locator('[data-actor="0"]').count(), 0);
    assert.match(await page.locator('[data-card="forward"] .card-art').getAttribute('src'), /qinghe\/Forward-v2/);
    assert.equal(await page.locator('[data-card="forward"] .card-art-qinghe-forward').count(), 1);
    await page.screenshot({ path: 'test-results/qinghe-ultimate.png' });
    const heroTop = await page.locator('[data-actor="hero"]').evaluate(actor => actor.style.top);
    await page.locator('[data-card="forward"]').click();
    await page.locator('.tile[data-x="2"][data-y="1"]').click();
    await page.waitForFunction(() => document.getElementById('game')?.getAttribute('aria-busy') === 'false');
    assert.notEqual(await page.locator('[data-actor="hero"]').evaluate(actor => actor.style.top), heroTop);
    assert.equal(await page.locator('[data-card="forward"]').count(), 1);
    await page.locator('[data-test-action="opening"]').click();
    await page.locator('[data-card="advance"]').first().click();
    await page.locator('.tile[data-x="2"][data-y="1"]').click();
    await page.waitForFunction(() => document.getElementById('game')?.getAttribute('aria-busy') === 'false');
    assert.match(await page.locator('#actions').getAttribute('aria-label'), /充能 1 \/ 4/);
    await page.locator('[data-card="sweep"]').click();
    assert.equal(await page.locator('[data-card="sweep"]').count(), 1);
    assert.equal(await page.locator('.tile.sweep-range').count(), 8);
    assert.equal(await page.locator('.target-mark').count(), 0);
    assert.equal(await page.locator('[data-actor="0"].sweep-victim-preview').count(), 1);
    assert.equal(await page.locator('.tile.attack-range').count(), 8);
    await page.locator('.tile[data-x="1"][data-y="2"]').hover();
    assert.equal(await page.locator('.tile.sweep-active').count(), 8);
    assert.equal(await page.locator('.target-mark').count(), 0);
    assert.equal(await page.locator('[data-actor="0"].victim-preview').count(), 0);
    assert.equal(await page.locator('[data-actor="0"].sweep-victim-preview').count(), 1);
    await page.locator('.tile[data-x="2"][data-y="2"]').hover();
    assert.equal(await page.locator('.threat-mark').count(), 0);
    assert.ok(!(await page.locator('#game').innerText()).includes('目標未倒下'));
    await page.locator('.tile[data-x="1"][data-y="2"]').hover();
    await page.screenshot({ path: 'test-results/qinghe-sweep-preview.png' });
    await page.locator('.tile[data-x="1"][data-y="2"]').click();
    await page.waitForFunction(() => document.getElementById('game')?.getAttribute('aria-busy') === 'false');
    assert.equal(await page.locator('[data-actor="0"]').count(), 0);
    await page.screenshot({ path: 'test-results/qinghe-sweep.png' });
    await page.locator('[data-test-action="opening"]').click();
    await page.locator('[data-test-action="charge"]').click();
    for (let index = 0; index < 3; index++) await page.locator('[data-test-action="energy"]').click();
    const souls = await page.locator('#energy-count .action-pip').evaluateAll(nodes => nodes.map(node => ({ left: node.getBoundingClientRect().left, z: Number(getComputedStyle(node).zIndex) })));
    assert.equal(souls.length, 5);
    for (let index = 1; index < souls.length; index++) {
      assert.ok(souls[index].left > souls[index - 1].left);
      assert.ok(souls[index].z < souls[index - 1].z);
    }
    await page.waitForFunction(() => !document.getElementById('game')?.classList.contains('dealing-hand'));
    await page.screenshot({ path: 'test-results/qinghe-five-souls.png' });
    await page.locator('[data-test-action="hand"]').click();
    assert.equal(await page.locator('.card').count(), 5);
    await page.locator('#actions').click();
    await page.locator('#ultimate-exchange').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-card="dawnSpear"]').count(), 0);
    await page.locator('#ultimate-exchange-options button').first().click();
    await page.locator('#ultimate-reveal').waitFor({ state: 'visible' });
    assert.equal(await page.locator('[data-card="dawnSpear"]').count(), 0);
    await page.locator('#ultimate-reveal').waitFor({ state: 'hidden' });
    await page.locator('.ultimate-draw-card').waitFor({ state: 'hidden' });
    await page.waitForFunction(() => document.getElementById('game')?.getAttribute('aria-busy') === 'false');
    assert.equal(await page.locator('.card').count(), 5);
    assert.equal(await page.locator('[data-card="dawnSpear"]').count(), 1);
    assert.deepEqual(errors, []);
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
