const assert = require('node:assert/strict');
module.exports = async function checkRogue(page, output) {
  const idle = () => page.waitForFunction(() => document.querySelector('#game').getAttribute('aria-busy') === 'false');
  await require('./village-flow.cjs').chooseCharacter(page, 'rogue');
  await page.locator('#open-dungeons').click();
  await page.locator('#start-game').click();
  assert.deepEqual(await page.locator('#hand .card').evaluateAll(nodes => nodes.map(n => n.dataset.card)), ['throw', 'shadow', 'whirl']);
  const origin = await page.locator('[data-actor="hero"]').getAttribute('style');
  await page.locator('[data-card="throw"]').click();
  await page.locator('.tile[data-x="2"][data-y="2"]').hover();
  assert.equal(await page.locator('#ghost').isVisible(), false);
  await page.locator('.tile[data-x="2"][data-y="2"]').click();
  await idle();
  assert.equal(await page.locator('[data-actor="hero"]').getAttribute('style'), origin);
  assert.equal(await page.locator('.ground-knife').count(), 1);
  assert.equal(await page.locator('[data-actor="0"]').count(), 0);
  if (output) await page.screenshot({path: `${output}/rogue-ground-knife.png`});
  await page.locator('[data-card="shadow"]').click();
  await page.locator('.tile[data-x="2"][data-y="2"]').click();
  await idle();
  assert.equal(await page.locator('#turn').textContent(), '第 1 回合');
  assert.match(await page.locator('#actions').textContent(), /1\/2/);
  assert.equal(await page.locator('.ground-knife').count(), 0);
  assert.equal(await page.locator('[data-card="knife"]').count(), 1);
  assert.notEqual(await page.locator('[data-actor="hero"]').getAttribute('style'), origin);
  if (output) await page.screenshot({path: `${output}/rogue-knife-pickup.png`});
  assert.equal(await page.locator('#hand .card').count(), 2);
  await page.locator('#end-turn').click();
  await idle();
  await page.locator('#end-turn').click();
  await idle();
  const beforeWhirl = await page.locator('#actors .actor:not(.hero)').count();
  const heroBeforeWhirl = await page.locator('[data-actor="hero"]').getAttribute('style');
  await page.locator('[data-card="whirl"]').click();
  assert.ok((await page.locator('.tile[data-x="2"][data-y="2"]').getAttribute('class')).includes('legal'));
  if (output) await page.screenshot({path: `${output}/rogue-whirl-preview.png`});
  await page.locator('.tile[data-x="2"][data-y="2"]').click();
  await idle();
  assert.equal(await page.locator('[data-actor="hero"]').getAttribute('style'), heroBeforeWhirl);
  assert.ok((await page.locator('#actors .actor:not(.hero)').count()) < beforeWhirl);
  await page.reload();
};
