const assert = require('node:assert/strict');
module.exports = async function checkRogue(page, output) {
  const idle = () => page.waitForFunction(() => document.querySelector('#game').getAttribute('aria-busy') === 'false');
  await require('./village-flow.cjs').chooseCharacter(page, 'rogue');
  await page.locator('#open-dungeons').click();
  await page.locator('#start-game').click();
  assert.deepEqual(await page.locator('#hand .card').evaluateAll(nodes => nodes.map(n => n.dataset.card)), ['throw', 'shadow', 'whirl']);
  const origin = await page.locator('[data-actor="hero"]').getAttribute('style');
  await page.locator('[data-card="throw"]').click();
  await page.locator('.tile[data-x="2"][data-y="2"]').hover();
  assert.equal(await page.locator('#ghost').isVisible(), false);
  await page.locator('.tile[data-x="2"][data-y="2"]').click();
  await idle();
  assert.equal(await page.locator('[data-actor="hero"]').getAttribute('style'), origin);
  assert.equal(await page.locator('.ground-knife').count(), 1);
  assert.equal(await page.locator('[data-actor="0"]').count(), 0);
  if (output) await page.screenshot({path: `${output}/rogue-ground-knife.png`});
  await page.locator('[data-card="shadow"]').click();
  await page.locator('.tile[data-x="2"][data-y="2"]').click();
  await idle();
  assert.equal(await page.locator('#turn').textContent(), '第 1 回合');
  assert.match(await page.locator('#actions').textContent(), /0\/2/);
  assert.equal(await page.locator('.ground-knife').count(), 0);
  assert.equal(await page.locator('#bonus-hand [data-card="knife"]').isEnabled(), true);
  assert.equal(await page.locator('[data-card="whirl"]').isDisabled(), true);
  if (output) await page.screenshot({path: `${output}/rogue-free-knife.png`});
  await page.locator('[data-card="knife"]').click();
  await page.locator('.tile[data-x="2"][data-y="1"]').click();
  await idle();
  assert.equal(await page.locator('#turn').textContent(), '第 2 回合');
  assert.equal(await page.locator('[data-card="knife"]').count(), 0);
  assert.equal(await page.locator('#hand .card').count(), 3);
  await page.reload();
};
